### ISSUE TITLE
New task workflow form 

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#135]
**Details :-**  https://github.com/Real-Dev-Squad/website-backend/issues/460

**Tasks :-** 

- [x] Remove startedOn input field from the form, and endsOn input field will be hidden by default
- [x] Default status field should be **AVAILABLE**(or UNASSIGNED decision pending)
- [x] When the status field is selected as **ASSIGNED** show assignee field and make it compulsory and show endsOn date and default endsOn date is 14 days
- [x] When a new task is created startedOn will be computed if the task is assigned else ignored
