### ISSUE TITLE
Home page for individual User Screen in User Management Service

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-dashboard#228]
Create a Home Page for the User. Which will have the following 4 sections.

- [ ] Academic / Professional Details
- [ ] Skills
- [ ] Tasks
- [ ] Availability

All 4 sections should be expanded when clicking on the respective expansion button on the right.
Apart from these Sections, it should also display the Name, Image & social links of the User

On Clicking the Dropdowns the respective section would expand. It will contain the following details.

### Academic / Professional Details Section
- [ ] College / Company
- [ ] Current Year / Years of Experience
- [ ] Looking for Job / Internship

### Tasks Details Section
- [ ] List of all the tasks completed by the users

### Availability Details Section

- [ ] OOO Status
- [ ] If OOO then Since, Return Date, No of Days, Reason
- [ ] If Not OOO then-No of hours available this month, No of hours remaining.

In the next version, we will change the no of hours remaining to a slider and also add logs if the user changes this available hour from my site.

Note: The page should be responsive. We need to also write unit and integration tests and also take care of accessibility.

Refer to this [figma link](https://www.figma.com/file/UsEeJHsLrJp9P0lUc5dDl1/UM-Service?node-id=0%3A1) for the design. You can tweak the design if you can make it look better.

**Comment by manish591** [comment]
can I take this task?

**Comment by heyrandhir** [comment]
> can I take this task?

Sure, Manish. Thanks for picking it up. Please let me know the ETA.
